modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/rhysdh540/createunlimited/issues"
license = "GPL-3.0-or-later"

[[mods]]
modId = "createunlimited"
version = "${version}"
displayName = "Create Unlimited"
authors = "rdh"
description = '''
Remove all the limits!
'''
logoFile = "icon.png"

[[dependencies.createunlimited]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createunlimited]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createunlimited]]
modId="create"
mandatory=true
versionRange="[${create},)"
ordering="AFTER"
side="BOTH"
