modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/rhysdh540/createunlimited/issues"
license = "GPL-3.0-or-later"

[[mods]]
modId = "createunlimited"
version = "0.7.0-beta.1"
displayName = "Create Unlimited"
authors = "rdh"
description = "Remove all the limits!"
logoFile = "cu.png"

[[dependencies.createunlimited]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createunlimited]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.createunlimited]]
modId="create"
mandatory=true
versionRange="[6.0.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="createunlimited.mixins.json"