name: I found a bug!
description: Report an issue with Create Unlimited.
title: "[Bug] "
labels: ["bug"]
body:
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Reproduction Steps
        description: Tell us about the steps to reproduce the bug.
        value: |
          1.
          2.
          3.
          ...
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Expected Result
        description: A clear and concise description of what you expected to happen
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Log
        description: Please add a **link** to the crash report or log that was created when this issue occurred. You can upload the crash report to a site like https://mclo.gs/ or https://gist.github.com. Please **do not** paste the whole crash report in this issue.
      validations:
        required: true
  -   type: input
      attributes:
        label: Operating System
        description: The operating system you were using when the bug occurred
        placeholder: Windows 17
      validations:
        required: true
  -   type: input
      attributes:
        label: Mod Build
        description: The build number of the mod you were using when the bug occurred. This is usually the last numbers of the mod version (eg 0.5.0-**69**)
        placeholder: "69"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occurred
        options:
          - "1.19.2"
          - "1.20.1"
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Modloader
        description: The mod loader you are playing Minecraft with
        options:
          - Fabric
          - Forge
          - Quilt
      validations:
        required: true
  -   type: input
      attributes:
        label: Modloader Version
        description: The version of your selected modloader you were using when the bug occured
        placeholder: 0.14.22
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Other Mods
        description: Please list any other mods that were running when the crash happened.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Additional Context
        description: Add any extra context about the bug here
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this bug report and help improve Create Unlimited!"
