name: build
on: [ pull_request, push ]

jobs:
    skip:
        runs-on: ubuntu-latest
        steps:
            -   name: send skipped message
                uses: appleboy/discord-action@v1.0.0
                if: "startsWith(github.event.head_commit.message, '[skip]')"
                with:
                    webhook_id: ${{ secrets.WEBHOOK_ID }}
                    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                    args: '# Build #${{ github.run_number }} skipped'

    build:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[skip]')"
        strategy:
            matrix:
                java: [ 17 ]
                mc_version: [ 1.19.2, 1.20.1 ]
        steps:
            -   name: checkout
                uses: actions/checkout@v3

            -   name: install java ${{ matrix.java }}
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ matrix.java }}
                    distribution: zulu

            - name: cache gradle
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/loom-cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle

            -   name: give gradlew permissions
                run: chmod +x gradlew

            -   name: build
                run: ./gradlew clean assemble -PmcVer=${{ matrix.mc_version }}

            -   name: move artifacts
                run: ./gradlew moveJars -PmcVer=${{ matrix.mc_version }}

            -  name: upload non-merged artifacts
               uses: actions/upload-artifact@v3
               with:
                    name: cu-artifacts
                    path: artifacts/unmerged/**/*.jar

            -   name: upload merged artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: cu-artifacts-merged
                    path: artifacts/merged/*.jar

            -   name: send failure message
                if: failure()
                uses: appleboy/discord-action@v1.0.0
                with:
                    webhook_id: ${{ secrets.WEBHOOK_ID }}
                    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                    args: '# Build #${{ github.run_number }} failed'

            -   name: send artifacts to webhook
                if: success()
                uses: appleboy/discord-action@v1.0.0
                with:
                    webhook_id: ${{ secrets.WEBHOOK_ID }}
                    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                    message: '# Build #${{ github.run_number }}'
                    file: |
                        artifacts/merged/*.jar