name: build
on: [ pull_request, push ]

jobs:
    skip:
        runs-on: ubuntu-latest
        if: "startsWith(github.event.head_commit.message, '[skip]')"
        steps:
            -   name: send skipped message
                uses: appleboy/discord-action@v1.0.0
                with:
                    webhook_id: ${{ secrets.WEBHOOK_ID }}
                    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                    args: '# Build #${{ github.run_number }} skipped'

    build:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[skip]')"
        strategy:
            matrix:
                java: [ 17 ]
        steps:
            -   name: checkout
                uses: actions/checkout@v3

            -   name: install java ${{ matrix.java }}
                uses: actions/setup-java@v3
                with:
                    java-version: ${{ matrix.java }}
                    distribution: zulu
                    cache: gradle

            -   name: cache loom
                uses: actions/cache@v3
                with:
                    path: ~/.gradle/loom-cache
                    key: loom-cache-${{ runner.os }}-gradle-${{ hashFiles('~/.gradle/loom-cache/**') }}
                    restore-keys: loom-cache-${{ runner.os }}-gradle

            -   name: give scripts execution permissions
                run: chmod +x gradlew buildAll

            -   name: Run build script
                run: ./buildAll

            -  name: upload non-merged artifacts
               uses: actions/upload-artifact@v3
               with:
                    name: artifacts
                    path: ./artifacts/**

            -   name: upload merged artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: merged-artifacts
                    path: ./build/libs/merged/*.jar

            -   name: send artifacts to webhook
                if: success()
                uses: appleboy/discord-action@v1.0.0
                with:
                    webhook_id: ${{ secrets.WEBHOOK_ID }}
                    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                    args: '# Build #${{ github.run_number }}'
                    file: build/libs/merged/*.jar

            -   name: send failure message
                if: failure()
                uses: appleboy/discord-action@v1.0.0
                with:
                    webhook_id: ${{ secrets.WEBHOOK_ID }}
                    webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                    args: '# Build #${{ github.run_number }} failed'