name: build
on: [ workflow_dispatch, push, pull_request ]

jobs:
    build:
        if: "!contains(github.event.head_commit.message, '[skip]')"
        runs-on: ubuntu-20.04
        steps:
            -   name: checkout
                uses: actions/checkout@v4

            -   name: setup java
                uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: 17

            -   name: setup gradle
                uses: gradle/gradle-build-action@v2.4.2
                with:
                    cache-read-only: false

            -   name: do the build
                run: ./gradlew assemble

            -   name: squishy
                run: ./gradlew squishJar

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: unlimited-artifacts-${{ github.run_id }}
                    path: |
                        build/libs/merged/*.jar
                        */build/libs/*.jar