name: build
on: [ workflow_dispatch, push, pull_request ]

jobs:
    build:
        if: "!contains(github.event.head_commit.message, '[skip]')"
        runs-on: ubuntu-latest
        steps:
            -   name: checkout
                uses: actions/checkout@v4

            -   name: setup java
                uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: 21

            -   name: setup gradle
                uses: gradle/actions/setup-gradle@v4
                with:
                    cache-encryption-key: ${{ SECRETS.GRADLE_ENCRYPTION_KEY }}

            -   name: do the build
                run: ./gradlew assemble --stacktrace

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: unlimited-artifacts-v${{ github.run_number }}
                    path: |
                        build/libs/*
                        build/distributions/*